### ISSUE TITLE
Ruby version installation issue on ubuntu-24.04-x64 runner

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#160]
### Current Behavior

I encountered an error when trying to run a GitHub Actions workflow that uses Ruby setup on the `ubuntu-24.04-x64` runner. It seems that the current runner is detected as self-hosted because the platform does not match a GitHub-hosted runner image, or the image is deprecated.

Here's the relevant portion of the error message:
```
Error: The current runner (ubuntu-24.04-x64) was detected as self-hosted because the platform does not match a GitHub-hosted runner image (or that image is deprecated and no longer supported).
```

The issue appears when using the `ruby/setup-ruby@v1` action, which specifies using `ruby-version: default` and relies on the `.ruby-version` file, which is set to Ruby version 3.1.3.

**Proposed Solutions:**

1. **Downgrade to `ubuntu-22.04` runner:**
   The `ubuntu-24.04` runner may not be fully supported by some Ruby setup actions. Downgrading the runner to `ubuntu-22.04` or `ubuntu-20.04` could resolve this issue while waiting for updates. This can be done by specifying the runner version in the workflow YAML:
   ```yaml
   runs-on: ubuntu-22.04
   ```

2. **Install Ruby manually on the runner:**
   If downgrading is not an option, manually installing Ruby on the `ubuntu-24.04` runner using the instructions provided in the error message could work. Here is an example of how to install Ruby manually:
   ```yaml
   - name: Install Ruby 3.1.3
     run: |
       ruby-build 3.1.3 /opt/hostedtoolcache/Ruby/3.1.3/x64
       touch /opt/hostedtoolcache/Ruby/3.1.3/x64.complete
   ```

3. **Use an alternative Ruby setup action or approach:**
   Another option is to investigate alternative Ruby setup actions, such as configuring Ruby with `rbenv` or another Ruby version management tool as described in the error message.

**Expected Outcome:**
The workflow should successfully install and use Ruby 3.1.3 on the `ubuntu-24.04` runner, or the issue should be resolved by using a supported GitHub-hosted runner.

**Environment:**
- GitHub Actions runner: `ubuntu-24.04-x64`
- Ruby version: 3.1.3
- Ruby setup action: `ruby/setup-ruby@v1`

### Steps To Reproduce

1. Set up a workflow that uses the following action:
   ```yaml
   - name: Setup Ruby
     uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42
     with:
       bundler-cache: true
       cache-version: 0
   ```
2. Use the `ubuntu-24.04` runner.
3. Observe the failure during Ruby setup.

### Anything else?

- <https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch/actions/runs/11337118567>
