### ISSUE TITLE
Change default font to `Euclid Circular B`

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#22]
### Describe what feature you'd like. Pseudo-code, mockups, or screenshots of similar solutions are encouraged!

We could implement it as in https://github.com/Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch-CB-gh/compare/sgb...maehr:forschung.stadtgeschichtebasel.ch:sgb

- `_data/theme.yml`

```yml
text-color: "#000000"
link-color: "#0077BB"
base-font-family: "Euclid Circular B"
```

- `_sass/_custom.scss`
- `assets/fonts/EuclidCircularB-Medium.otf`
- ...

### What type of pull request would this be?

Enhancement
