### ISSUE TITLE
Incorrect URL Configuration in _config.yml File

### ISSUE THREAD

**Issue by maehr** [Stadt-Geschichte-Basel/forschung.stadtgeschichtebasel.ch#29]
### Current Behavior

The current configuration of the `url` and `baseurl` in the `_config.yml` file does not reflect the intended production URL of the website. This misconfiguration could lead to issues with site navigation, resource loading, and overall functionality of the website.

**Current Configuration:**
```yaml
# _config.yml
# site domain, full URL to the production location of your collection
url:  https://Stadt-Geschichte-Basel.github.io
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl: /forschung.stadtgeschichtebasel.ch
```

**Expected Configuration:**
```yaml
# _config.yml
# site domain, full URL to the production location of your collection
url:  https://forschung.stadtgeschichtebasel.ch
# path to location on the domain if necessary e.g. /digital/hjccc
baseurl:
```

**Impact of Issue:**
- Hyperlinks, resource references, and API calls that rely on the base URL might be pointing to incorrect paths.
- Visitors might experience broken links or failed resource loadings (like images, stylesheets, scripts).
- SEO and analytics could be adversely affected due to the incorrect URL.

### Steps To Reproduce

1. Open the `_config.yml` file in the repository.
2. Observe the current configuration of the `url` and `baseurl` fields.
3. Compare with the expected configuration.
